In [10]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns',None)

In [11]:
df = pd.read_csv('data/data_normelized_binary_v2.csv', low_memory=False)

In [12]:
df.drop(columns=['trip_id', 'pickup','CommissionPercent','epay_method', 'epay_type',
                 'assigned_at_rejection_type', 'destination', 'first_finished_driver'], inplace=True)

In [13]:

# Convert date-time columns to datetime
date_columns = ['requested_at', 'updated_at', 'created_at', 'accepted_at', 
                'started_at', 'cancel_date_time', 'assigned_at']
for col in date_columns:
    df[col] = pd.to_datetime(df[col], format='mixed')  # or omit format if mixed date formats are present
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,assigned_at,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,driver_profile_gender,final_driver_rating,final_driver_wilaya,rider_rating,driver_rating,yassir2driver,driver2yassir,discount_ratio_percent,driver,took_trip
0,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:14.830000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePSUralyqcKVNakVKyfpgqvUXUzpZ6gm_5aQ...,0
1,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:15.061000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePFrk96bEft8WGJTStDS5zCx96HLHiNZ-2k8...,0
2,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:15.061000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePtCB-IqV5JTijXkgcUUSl3bhYQQ-WljKidI...,1
3,2023-07-21 12:58:17.725000+00:00,2023-07-21 13:26:37.723000+00:00,2023-07-21 12:58:17.728000+00:00,2023-07-21 12:58:34.588000+00:00,2023-07-21 13:11:25.727000+00:00,NaT,2023-07-21 12:58:17.876000+00:00,0.074419,gAAAAABnP1eDPURjuV8jOeUoKidjs1W2DtLIrp6nekFcZb...,/,5.0,10928,869.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,HOMME,4.6,16.0,5.0,NaN,3.083333,-0.504854,0.3,gAAAAABnP1eTMKGDLYvfynTB6KpwRB5-STMOOFTdrlaSN5...,0
4,2023-07-21 12:58:17.725000+00:00,2023-07-21 13:26:37.723000+00:00,2023-07-21 12:58:17.728000+00:00,2023-07-21 12:58:34.588000+00:00,2023-07-21 13:11:25.727000+00:00,NaT,2023-07-21 12:58:17.876000+00:00,0.074419,gAAAAABnP1eDPURjuV8jOeUoKidjs1W2DtLIrp6nekFcZb...,/,5.0,10928,869.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,HOMME,4.6,16.0,5.0,NaN,3.083333,-0.504854,0.3,gAAAAABnP1ePSIWNOo5ldpsuJccvLMMixqQ3sUHweqYgak...,1

In [14]:
df['request_hour'] = df['requested_at'].dt.hour
df['request_day_of_week'] = df['requested_at'].dt.dayofweek
df['request_month'] = df['requested_at'].dt.month
df['request_day_of_month'] = df['requested_at'].dt.day
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,assigned_at,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,driver_profile_gender,final_driver_rating,final_driver_wilaya,rider_rating,driver_rating,yassir2driver,driver2yassir,discount_ratio_percent,driver,took_trip,request_hour,request_day_of_week,request_month,request_day_of_month
0,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:14.830000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePSUralyqcKVNakVKyfpgqvUXUzpZ6gm_5aQ...,0,12,2,2,22
1,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:15.061000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePFrk96bEft8WGJTStDS5zCx96HLHiNZ-2k8...,0,12,2,2,22
2,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:15.061000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePtCB-IqV5JTijXkgcUUSl3bhYQQ-WljKidI...,1,12,2,2,22
3,2023-07-21 12:58:17.725000+00:00,2023-07-21 13:26:37.723000+00:00,2023-07-21 12:58:17.728000+00:00,2023-07-21 12:58:34.588000+00:00,2023-07-21 13:11:25.727000+00:00,NaT,2023-07-21 12:58:17.876000+00:00,0.074419,gAAAAABnP1eDPURjuV8jOeUoKidjs1W2DtLIrp6nekFcZb...,/,5.0,10928,869.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,HOMME,4.6,16.0,5.0,NaN,3.083333,-0.504854,0.3,gAAAAABnP1eTMKGDLYvfynTB6KpwRB5-STMOOFTdrlaSN5...,0,12,4,7,21
4,2023-07-21 12:58:17.725000+00:00,2023-07-21 13:26:37.723000+00:00,2023-07-21 12:58:17.728000+00:00,2023-07-21 12:58:34.588000+00:00,2023-07-21 13:11:25.727000+00:00,NaT,2023-07-21 12:58:17.876000+00:00,0.074419,gAAAAABnP1eDPURjuV8jOeUoKidjs1W2DtLIrp6nekFcZb...,/,5.0,10928,869.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,HOMME,4.6,16.0,5.0,NaN,3.083333,-0.504854,0.3,gAAAAABnP1ePSIWNOo5ldpsuJccvLMMixqQ3sUHweqYgak...,1,12,4,7,21

In [15]:
df.columns

Index(['requested_at', 'updated_at', 'created_at', 'accepted_at', 'started_at',
       'cancel_date_time', 'assigned_at', 'original_cost', 'rider',
       'rider_profile_gender', 'rider_profile_rating', 'estimated_distance',
       'estimated_eta', 'is_coupon', 'isMultiStop', 'discount', 'is_booked',
       'radius', 'dcc_distance', 'final_status', 'driver_profile_gender',
       'final_driver_rating', 'final_driver_wilaya', 'rider_rating',
       'driver_rating', 'yassir2driver', 'driver2yassir',
       'discount_ratio_percent', 'driver', 'took_trip', 'request_hour',
       'request_day_of_week', 'request_month', 'request_day_of_month'],
      dtype='object')

In [16]:
acceptance_rate = df.groupby(['driver', 'request_day_of_week'])['took_trip'].agg(
    total_requests=('count'),
    accepted_trips=('sum'),
    acceptance_rate=('mean')
).reset_index()

# Rename columns for clarity
acceptance_rate.columns = [
    'Driver', 
    'Day of Week', 
    'Total Requests', 
    'Accepted Trips', 
    'Acceptance Rate'
]

# Sort values for readability
acceptance_rate.sort_values(['Driver', 'Day of Week'], inplace=True)
acceptance_rate.head()

,Driver,Day of Week,Total Requests,Accepted Trips,Acceptance Rate
0,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,0,8,3,0.375000
1,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,1,1,1,1.000000
2,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,2,1,1,1.000000
3,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,3,3,2,0.666667
4,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,6,4,4,1.000000

In [17]:
acceptance_rates = df.groupby(['driver', 'request_day_of_week'])['took_trip'].mean().reset_index()
acceptance_rates.head()

,driver,request_day_of_week,took_trip
0,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,0,0.375000
1,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,1,1.000000
2,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,2,1.000000
3,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,3,0.666667
4,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,6,1.000000

In [18]:
acceptance_rates.rename(columns={'took_trip': 'average_acceptance_rate'}, inplace=True)

# Step 3: Pivot the table to create 7 columns, one for each day of the week
acceptance_rate_pivot = acceptance_rates.pivot(index='driver', 
                                               columns='request_day_of_week', 
                                               values='average_acceptance_rate')

# Rename columns for clarity
acceptance_rate_pivot.columns = [
    'acceptance_rate_monday', 'acceptance_rate_tuesday', 'acceptance_rate_wednesday',
    'acceptance_rate_thursday', 'acceptance_rate_friday', 'acceptance_rate_saturday',
    'acceptance_rate_sunday'
]

# Step 4: Merge the pivoted table back into the original dataframe based on the 'driver' column
df = df.merge(acceptance_rate_pivot, on='driver', how='left')
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,assigned_at,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,driver_profile_gender,final_driver_rating,final_driver_wilaya,rider_rating,driver_rating,yassir2driver,driver2yassir,discount_ratio_percent,driver,took_trip,request_hour,request_day_of_week,request_month,request_day_of_month,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday
0,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:14.830000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePSUralyqcKVNakVKyfpgqvUXUzpZ6gm_5aQ...,0,12,2,2,22,0.089947,0.093333,0.062827,0.126667,0.116959,0.110169,0.101190
1,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:15.061000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePFrk96bEft8WGJTStDS5zCx96HLHiNZ-2k8...,0,12,2,2,22,0.146341,0.147541,0.142857,0.222222,0.190476,0.269841,0.154930
2,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:15.061000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePtCB-IqV5JTijXkgcUUSl3bhYQQ-WljKidI...,1,12,2,2,22,0.454545,0.363636,0.500000,0.600000,0.900000,0.769231,0.500000
3,2023-07-21 12:58:17.725000+00:00,2023-07-21 13:26:37.723000+00:00,2023-07-21 12:58:17.728000+00:00,2023-07-21 12:58:34.588000+00:00,2023-07-21 13:11:25.727000+00:00,NaT,2023-07-21 12:58:17.876000+00:00,0.074419,gAAAAABnP1eDPURjuV8jOeUoKidjs1W2DtLIrp6nekFcZb...,/,5.0,10928,869.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,HOMME,4.6,16.0,5.0,NaN,3.083333,-0.504854,0.3,gAAAAABnP1eTMKGDLYvfynTB6KpwRB5-STMOOFTdrlaSN5...,0,12,4,7,21,0.000000,NaN,NaN,NaN,0.000000,0.000000,NaN
4,2023-07-21 12:58:17.725000+00:00,2023-07-21 13:26:37.723000+00:00,2023-07-21 12:58:17.728000+00:00,2023-07-21 12:58:34.588000+00:00,2023-07-21 13:11:25.727000+00:00,NaT,2023-07-21 12:58:17.876000+00:00,0.074419,gAAAAABnP1eDPURjuV8jOeUoKidjs1W2DtLIrp6nekFcZb...,/,5.0,10928,869.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,HOMME,4.6,16.0,5.0,NaN,3.083333,-0.504854,0.3,gAAAAABnP1ePSIWNOo5ldpsuJccvLMMixqQ3sUHweqYgak...,1,12,4,7,21,0.205128,0.190083,0.204082,0.168539,0.134328,0.181818,0.108434

In [19]:
acceptance_rate_pivot.fillna(0., inplace=True)
acceptance_rate_pivot.head()

,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday
driver,,,,,,,
gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m1cV92twQG_blNBqy9GgO_E2WAKayJFSsy1PSwEGctY2vpv3g9oBkRS1T_EB1VlwfTIEdmS8s8=,0.375000,1.0,1.00,0.666667,0.00000,0.000000,1.000000
gAAAAABnP1eP-0hm7X7pky2Su8OaitNnqLfuxHlIvp72tS7zhOr23d4HsWqEVhjjPTX7KyExOlr3g1pJ3jIVJSoxaqgRUQ52zqbU97UwKlH0PpR6VI_5d3A=,0.000000,0.0,0.00,0.000000,0.00000,1.000000,0.333333
gAAAAABnP1eP-1e8_PnLOHgnnTIA7AqnElVW3qWcnXWj1DCZpWEXsLKg6rxBCTSSAVhaoHyUoEjepuAC6T0ST2V3P_HLX61Ed-lEr5CL-Ta4LV-Z2KhCpW4=,0.000000,0.0,0.00,1.000000,0.00000,0.000000,0.000000
gAAAAABnP1eP-1ucYmfswPEFjak_y4ZqsfcF8jAtYSU5O9KDdmV9lDAwiCM4yLSKdQo2UtB1gSrpyYQsqtRM8uIf5XRWiG82l_wuYQn_u8jKMnE42cnNzuQ=,0.666667,0.0,0.00,0.000000,0.00000,1.000000,0.000000
gAAAAABnP1eP-21hNsK-jiTx3LjuHi7o2JE40VoKX7rMYtvl9tkn1Paoh7TsOGb26sVJS-RFXbEOszMOpZit2hMleplPhZRbQ9RSuqfnizklYMYxfFfrVwA=,0.058824,0.0,0.04,0.088889,0.03125,0.032258,0.125000

In [20]:
acceptance_rate_pivot.to_csv('data/acceptance_rate_pivot.csv')

In [21]:
columns_to_fill = ['acceptance_rate_monday', 'acceptance_rate_tuesday', 'acceptance_rate_wednesday', 'acceptance_rate_thursday',
                   'acceptance_rate_friday', 'acceptance_rate_saturday', 'acceptance_rate_sunday'
                   ]

df[columns_to_fill] = df[columns_to_fill].fillna(0.)

In [36]:
# from datetime import datetime
# import pytz

# def days_since_first_accepted(driver, df):
#     # Sort the dataframe by 'driver' and 'accepted_at' to ensure the first accepted trip appears first
#     df_sorted = df.sort_values(by=['driver', 'accepted_at'])
    
#     # Filter the dataframe based on the driver ID
#     matching_driver = df_sorted[df_sorted['driver'] == driver]
    
#     if matching_driver.empty:
#         return f"No driver found with ID {driver}"
    
#     # Get the first accepted trip for the matched driver
#     first_accepted_at = matching_driver.iloc[0]['accepted_at']
    
#     # Convert datetime.now() to UTC timezone (or match the timezone of your 'accepted_at' column)
#     utc_now = datetime.now(pytz.utc)
    
#     # Calculate the number of days since the first accepted trip
#     days_since_first = (utc_now - first_accepted_at).days  # Calculate days difference
    
#     return days_since_first

# # Example usage:
# driver = 'gAAAAABnP1ePf3MVWdbZLZILEbsaSfBvZxQneE3mqn3Thgo7ay4nQaco8zMqqgLDp_QDu3pIdQo4f8tt7ztz7ABuf7iasDYQpDng9Zm40okLr8-EakN17p4='  # Replace with the driver_id you want to check
# days = days_since_first_accepted(driver, df)
# print(f"Driver {driver} first accepted a trip {days} days ago.")

In [22]:
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,assigned_at,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,driver_profile_gender,final_driver_rating,final_driver_wilaya,rider_rating,driver_rating,yassir2driver,driver2yassir,discount_ratio_percent,driver,took_trip,request_hour,request_day_of_week,request_month,request_day_of_month,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday
0,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:14.830000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePSUralyqcKVNakVKyfpgqvUXUzpZ6gm_5aQ...,0,12,2,2,22,0.089947,0.093333,0.062827,0.126667,0.116959,0.110169,0.101190
1,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:15.061000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePFrk96bEft8WGJTStDS5zCx96HLHiNZ-2k8...,0,12,2,2,22,0.146341,0.147541,0.142857,0.222222,0.190476,0.269841,0.154930
2,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:15.061000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePtCB-IqV5JTijXkgcUUSl3bhYQQ-WljKidI...,1,12,2,2,22,0.454545,0.363636,0.500000,0.600000,0.900000,0.769231,0.500000
3,2023-07-21 12:58:17.725000+00:00,2023-07-21 13:26:37.723000+00:00,2023-07-21 12:58:17.728000+00:00,2023-07-21 12:58:34.588000+00:00,2023-07-21 13:11:25.727000+00:00,NaT,2023-07-21 12:58:17.876000+00:00,0.074419,gAAAAABnP1eDPURjuV8jOeUoKidjs1W2DtLIrp6nekFcZb...,/,5.0,10928,869.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,HOMME,4.6,16.0,5.0,NaN,3.083333,-0.504854,0.3,gAAAAABnP1eTMKGDLYvfynTB6KpwRB5-STMOOFTdrlaSN5...,0,12,4,7,21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,2023-07-21 12:58:17.725000+00:00,2023-07-21 13:26:37.723000+00:00,2023-07-21 12:58:17.728000+00:00,2023-07-21 12:58:34.588000+00:00,2023-07-21 13:11:25.727000+00:00,NaT,2023-07-21 12:58:17.876000+00:00,0.074419,gAAAAABnP1eDPURjuV8jOeUoKidjs1W2DtLIrp6nekFcZb...,/,5.0,10928,869.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,HOMME,4.6,16.0,5.0,NaN,3.083333,-0.504854,0.3,gAAAAABnP1ePSIWNOo5ldpsuJccvLMMixqQ3sUHweqYgak...,1,12,4,7,21,0.205128,0.190083,0.204082,0.168539,0.134328,0.181818,0.108434

In [23]:
driver_acceptance_stats = df.groupby('driver')['took_trip'].agg(
    total_requests='count',  # Total number of requests per driver
    total_accepted='sum'    # Total number of accepted requests per driver
).reset_index()

# Step 2: Calculate the acceptance rate
driver_acceptance_stats['acceptance_rate'] = (
    driver_acceptance_stats['total_accepted'] / driver_acceptance_stats['total_requests']
)

# Step 3: Merge these stats back into the original dataframe
df = df.merge(driver_acceptance_stats[['driver', 'acceptance_rate', 'total_accepted']], 
              on='driver', 
              how='left')

# Rename for clarity in the final dataframe
df.rename(columns={'total_accepted': 'acceptance_count'}, inplace=True)

In [24]:
driver_acceptance_stats.to_csv('/Users/hodhaifabenouaklil/Documents/Me/Competitions/YassirHackathon/V4/data/driver_acceptance_stats.csv')

In [25]:
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,assigned_at,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,driver_profile_gender,final_driver_rating,final_driver_wilaya,rider_rating,driver_rating,yassir2driver,driver2yassir,discount_ratio_percent,driver,took_trip,request_hour,request_day_of_week,request_month,request_day_of_month,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday,acceptance_rate,acceptance_count
0,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:14.830000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePSUralyqcKVNakVKyfpgqvUXUzpZ6gm_5aQ...,0,12,2,2,22,0.089947,0.093333,0.062827,0.126667,0.116959,0.110169,0.101190,0.098505,112
1,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:15.061000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePFrk96bEft8WGJTStDS5zCx96HLHiNZ-2k8...,0,12,2,2,22,0.146341,0.147541,0.142857,0.222222,0.190476,0.269841,0.154930,0.181118,94
2,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaT,2023-02-22 12:11:15.061000+00:00,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,HOMME,3.8,16.0,5.0,5.0,0.833333,-0.504854,NaN,gAAAAABnP1ePtCB-IqV5JTijXkgcUUSl3bhYQQ-WljKidI...,1,12,2,2,22,0.454545,0.363636,0.500000,0.600000,0.900000,0.769231,0.500000,0.586207,51
3,2023-07-21 12:58:17.725000+00:00,2023-07-21 13:26:37.723000+00:00,2023-07-21 12:58:17.728000+00:00,2023-07-21 12:58:34.588000+00:00,2023-07-21 13:11:25.727000+00:00,NaT,2023-07-21 12:58:17.876000+00:00,0.074419,gAAAAABnP1eDPURjuV8jOeUoKidjs1W2DtLIrp6nekFcZb...,/,5.0,10928,869.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,HOMME,4.6,16.0,5.0,NaN,3.083333,-0.504854,0.3,gAAAAABnP1eTMKGDLYvfynTB6KpwRB5-STMOOFTdrlaSN5...,0,12,4,7,21,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4,2023-07-21 12:58:17.725000+00:00,2023-07-21 13:26:37.723000+00:00,2023-07-21 12:58:17.728000+00:00,2023-07-21 12:58:34.588000+00:00,2023-07-21 13:11:25.727000+00:00,NaT,2023-07-21 12:58:17.876000+00:00,0.074419,gAAAAABnP1eDPURjuV8jOeUoKidjs1W2DtLIrp6nekFcZb...,/,5.0,10928,869.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,HOMME,4.6,16.0,5.0,NaN,3.083333,-0.504854,0.3,gAAAAABnP1ePSIWNOo5ldpsuJccvLMMixqQ3sUHweqYgak...,1,12,4,7,21,0.205128,0.190083,0.204082,0.168539,0.134328,0.181818,0.108434,0.173077,108

In [26]:
df.drop(columns=['requested_at', 'updated_at', 'created_at', 'accepted_at', 'started_at',
                 'cancel_date_time', 'assigned_at', 'rider_profile_gender', 'is_coupon',
                 'isMultiStop', 'is_booked', 'radius', 'dcc_distance', 'driver_profile_gender',
                 'final_driver_rating', 'final_driver_wilaya', 'rider_rating', 'driver_rating',
                 'discount_ratio_percent', 'request_day_of_month',
                 'rider', 'driver', 'final_status'
                 ], inplace=True)

In [27]:
df.head()

,original_cost,rider_profile_rating,estimated_distance,estimated_eta,discount,yassir2driver,driver2yassir,took_trip,request_hour,request_day_of_week,request_month,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday,acceptance_rate,acceptance_count
0,-0.499668,4.7,1315,285.0,0.25,0.833333,-0.504854,0,12,2,2,0.089947,0.093333,0.062827,0.126667,0.116959,0.110169,0.101190,0.098505,112
1,-0.499668,4.7,1315,285.0,0.25,0.833333,-0.504854,0,12,2,2,0.146341,0.147541,0.142857,0.222222,0.190476,0.269841,0.154930,0.181118,94
2,-0.499668,4.7,1315,285.0,0.25,0.833333,-0.504854,1,12,2,2,0.454545,0.363636,0.500000,0.600000,0.900000,0.769231,0.500000,0.586207,51
3,0.074419,5.0,10928,869.0,0.30,3.083333,-0.504854,0,12,4,7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4,0.074419,5.0,10928,869.0,0.30,3.083333,-0.504854,1,12,4,7,0.205128,0.190083,0.204082,0.168539,0.134328,0.181818,0.108434,0.173077,108

In [28]:
df.to_csv('data/used_in_test_preprocess.csv', index=False)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 644208 entries, 0 to 644207
Data columns (total 20 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   original_cost              644208 non-null  float64
 1   rider_profile_rating       644208 non-null  float64
 2   estimated_distance         644208 non-null  int64
 3   estimated_eta              644208 non-null  float64
 4   discount                   644208 non-null  float64
 5   yassir2driver              644208 non-null  float64
 6   driver2yassir              644208 non-null  float64
 7   took_trip                  644208 non-null  int64
 8   request_hour               644208 non-null  int32
 9   request_day_of_week        644208 non-null  int32
 10  request_month              644208 non-null  int32
 11  acceptance_rate_monday     644208 non-null  float64
 12  acceptance_rate_tuesday    644208 non-null  float64
 13  acceptance_rate_wednesday  644208 non-null  float64
 14  acceptance_rate_thursday   644208 non-null  float64
 15  acceptance_rate_friday     644208 non-null  float64
 16  acceptance_rate_saturday   644208 non-null  float64
 17  acceptance_rate_sunday     644208 non-null  float64
 18  acceptance_rate            644208 non-null  float64
 19  acceptance_count           644208 non-null  int64
dtypes: float64(14), int32(3), int64(3)
memory usage: 90.9 MB

In [30]:
df.head()

,original_cost,rider_profile_rating,estimated_distance,estimated_eta,discount,yassir2driver,driver2yassir,took_trip,request_hour,request_day_of_week,request_month,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday,acceptance_rate,acceptance_count
0,-0.499668,4.7,1315,285.0,0.25,0.833333,-0.504854,0,12,2,2,0.089947,0.093333,0.062827,0.126667,0.116959,0.110169,0.101190,0.098505,112
1,-0.499668,4.7,1315,285.0,0.25,0.833333,-0.504854,0,12,2,2,0.146341,0.147541,0.142857,0.222222,0.190476,0.269841,0.154930,0.181118,94
2,-0.499668,4.7,1315,285.0,0.25,0.833333,-0.504854,1,12,2,2,0.454545,0.363636,0.500000,0.600000,0.900000,0.769231,0.500000,0.586207,51
3,0.074419,5.0,10928,869.0,0.30,3.083333,-0.504854,0,12,4,7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0
4,0.074419,5.0,10928,869.0,0.30,3.083333,-0.504854,1,12,4,7,0.205128,0.190083,0.204082,0.168539,0.134328,0.181818,0.108434,0.173077,108

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 644208 entries, 0 to 644207
Data columns (total 20 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   original_cost              644208 non-null  float64
 1   rider_profile_rating       644208 non-null  float64
 2   estimated_distance         644208 non-null  int64
 3   estimated_eta              644208 non-null  float64
 4   discount                   644208 non-null  float64
 5   yassir2driver              644208 non-null  float64
 6   driver2yassir              644208 non-null  float64
 7   took_trip                  644208 non-null  int64
 8   request_hour               644208 non-null  int32
 9   request_day_of_week        644208 non-null  int32
 10  request_month              644208 non-null  int32
 11  acceptance_rate_monday     644208 non-null  float64
 12  acceptance_rate_tuesday    644208 non-null  float64
 13  acceptance_rate_wednesday  644208 non-null  float64
 14  acceptance_rate_thursday   644208 non-null  float64
 15  acceptance_rate_friday     644208 non-null  float64
 16  acceptance_rate_saturday   644208 non-null  float64
 17  acceptance_rate_sunday     644208 non-null  float64
 18  acceptance_rate            644208 non-null  float64
 19  acceptance_count           644208 non-null  int64
dtypes: float64(14), int32(3), int64(3)
memory usage: 90.9 MB

In [33]:
df.to_csv('data/data_final.csv', index=False)