In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
pd.set_option('display.max_columns',None)

In [2]:
df = pd.read_csv('data/test_normelized_v2.csv', low_memory=False)
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,pickup,destination,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,CommissionPercent,discount_ratio_percent,epay_method,epay_type,drivers_list
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaN,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,Boumerdès,Boumerdès,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.20,0.30,CASH,indirect,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...
1,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaN,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,Boumerdès,Alger,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.17,0.22,NaN,NaN,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1q...
2,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaN,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,Boumerdès,Boumerdès,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.17,0.00,CASH,indirect,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8...
3,2023-04-07 20:36:32.775000+00:00,2023-04-07 20:47:09.811000+00:00,2023-04-07 20:36:32.781000+00:00,2023-04-07 20:38:26.811000+00:00,NaN,2023-04-07 20:47:06.470000+00:00,gAAAAABnP1erj0EyqNN9zGSBc8X_8UdYSQr3gMBHLJVOCe...,Boumerdès,Boumerdès,1.820598,gAAAAABnP1eIXeZh19ghxI6UotZfVYmZLPLjZwcsRLcEPp...,/,4.5,30470,2074.0,1.0,NaN,0.09,False,9000,NaN,NOT_FINISHED,NaN,0.000000,0.932039,0.17,NaN,CASH,indirect,gAAAAABnP1eP4LFLt7j3HdeOoS0pVhrpCQSgABZ_GCyof9...
4,2023-06-21 08:10:02.683000+00:00,2023-06-21 08:20:13.543000+00:00,2023-06-21 08:10:02.686000+00:00,2023-06-21 08:10:36.983000+00:00,2023-06-21 08:16:15.408000+00:00,NaN,gAAAAABnP1el1Smd1cCYDnSI3t-PaR77jfPGMMAYlS9dug...,Boumerdès,Boumerdès,-0.465116,gAAAAABnP1eDsomcoP90eIbZjJmFHBaEihhZ92ZKl5rLqX...,/,4.7,3742,349.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.116505,0.20,0.00,CASH,NaN,gAAAAABnP1ePYYfZXcKAvUcL-ZBq35BMUFeN-yG7nrxa0...

In [3]:
len(df)

86625

In [4]:
df.drop(columns=['pickup','CommissionPercent','epay_method', 'epay_type', 'destination'], inplace=True)

In [5]:
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,drivers_list
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaN,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...
1,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaN,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1q...
2,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaN,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.00,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8...
3,2023-04-07 20:36:32.775000+00:00,2023-04-07 20:47:09.811000+00:00,2023-04-07 20:36:32.781000+00:00,2023-04-07 20:38:26.811000+00:00,NaN,2023-04-07 20:47:06.470000+00:00,gAAAAABnP1erj0EyqNN9zGSBc8X_8UdYSQr3gMBHLJVOCe...,1.820598,gAAAAABnP1eIXeZh19ghxI6UotZfVYmZLPLjZwcsRLcEPp...,/,4.5,30470,2074.0,1.0,NaN,0.09,False,9000,NaN,NOT_FINISHED,NaN,0.000000,0.932039,NaN,gAAAAABnP1eP4LFLt7j3HdeOoS0pVhrpCQSgABZ_GCyof9...
4,2023-06-21 08:10:02.683000+00:00,2023-06-21 08:20:13.543000+00:00,2023-06-21 08:10:02.686000+00:00,2023-06-21 08:10:36.983000+00:00,2023-06-21 08:16:15.408000+00:00,NaN,gAAAAABnP1el1Smd1cCYDnSI3t-PaR77jfPGMMAYlS9dug...,-0.465116,gAAAAABnP1eDsomcoP90eIbZjJmFHBaEihhZ92ZKl5rLqX...,/,4.7,3742,349.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.116505,0.00,gAAAAABnP1ePYYfZXcKAvUcL-ZBq35BMUFeN-yG7nrxa0...

In [6]:
# Convert date-time columns to datetime
date_columns = ['requested_at', 'updated_at', 'created_at', 'accepted_at', 
                'started_at', 'cancel_date_time']
for col in date_columns:
    df[col] = pd.to_datetime(df[col], format='mixed')  # or omit format if mixed date formats are present
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,drivers_list
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...
1,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1q...
2,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaT,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.00,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8...
3,2023-04-07 20:36:32.775000+00:00,2023-04-07 20:47:09.811000+00:00,2023-04-07 20:36:32.781000+00:00,2023-04-07 20:38:26.811000+00:00,NaT,2023-04-07 20:47:06.470000+00:00,gAAAAABnP1erj0EyqNN9zGSBc8X_8UdYSQr3gMBHLJVOCe...,1.820598,gAAAAABnP1eIXeZh19ghxI6UotZfVYmZLPLjZwcsRLcEPp...,/,4.5,30470,2074.0,1.0,NaN,0.09,False,9000,NaN,NOT_FINISHED,NaN,0.000000,0.932039,NaN,gAAAAABnP1eP4LFLt7j3HdeOoS0pVhrpCQSgABZ_GCyof9...
4,2023-06-21 08:10:02.683000+00:00,2023-06-21 08:20:13.543000+00:00,2023-06-21 08:10:02.686000+00:00,2023-06-21 08:10:36.983000+00:00,2023-06-21 08:16:15.408000+00:00,NaT,gAAAAABnP1el1Smd1cCYDnSI3t-PaR77jfPGMMAYlS9dug...,-0.465116,gAAAAABnP1eDsomcoP90eIbZjJmFHBaEihhZ92ZKl5rLqX...,/,4.7,3742,349.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.116505,0.00,gAAAAABnP1ePYYfZXcKAvUcL-ZBq35BMUFeN-yG7nrxa0...

In [7]:
df['request_hour'] = df['requested_at'].dt.hour
df['request_day_of_week'] = df['requested_at'].dt.dayofweek
df['request_month'] = df['requested_at'].dt.month
df['request_day_of_month'] = df['requested_at'].dt.day
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,drivers_list,request_hour,request_day_of_week,request_month,request_day_of_month
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...,8,1,6,27
1,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1q...,14,5,6,24
2,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaT,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.00,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8...,16,0,6,26
3,2023-04-07 20:36:32.775000+00:00,2023-04-07 20:47:09.811000+00:00,2023-04-07 20:36:32.781000+00:00,2023-04-07 20:38:26.811000+00:00,NaT,2023-04-07 20:47:06.470000+00:00,gAAAAABnP1erj0EyqNN9zGSBc8X_8UdYSQr3gMBHLJVOCe...,1.820598,gAAAAABnP1eIXeZh19ghxI6UotZfVYmZLPLjZwcsRLcEPp...,/,4.5,30470,2074.0,1.0,NaN,0.09,False,9000,NaN,NOT_FINISHED,NaN,0.000000,0.932039,NaN,gAAAAABnP1eP4LFLt7j3HdeOoS0pVhrpCQSgABZ_GCyof9...,20,4,4,7
4,2023-06-21 08:10:02.683000+00:00,2023-06-21 08:20:13.543000+00:00,2023-06-21 08:10:02.686000+00:00,2023-06-21 08:10:36.983000+00:00,2023-06-21 08:16:15.408000+00:00,NaT,gAAAAABnP1el1Smd1cCYDnSI3t-PaR77jfPGMMAYlS9dug...,-0.465116,gAAAAABnP1eDsomcoP90eIbZjJmFHBaEihhZ92ZKl5rLqX...,/,4.7,3742,349.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.116505,0.00,gAAAAABnP1ePYYfZXcKAvUcL-ZBq35BMUFeN-yG7nrxa0...,8,2,6,21

In [8]:
df['drivers_list'] = df['drivers_list'].apply(lambda x: x.split(',') if x is not None else [])

In [9]:
df['drivers_list'].iloc[0]

['gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8klsF8JyiCKbr3ryY-3hGh3Fap_GMPjfC3k_RrbZp86eIep31ZtKQ2lnGKS1qVf_hVrZsuFGtaw2k=',
 ' gAAAAABnP1ePWq-xbCGkf2IHHHmTawUmuYfrFnE6_bN7OxU7_nwUeC1gH93mSUhvKAK6ekDJHgrK3BeEDB4tF-EUfmLJU5B_aI5uaqFM1sYxoufHdtSFBl0=']

In [10]:
df = df.explode('drivers_list')

In [11]:
df['drivers_list'] = df['drivers_list'].str.strip()

In [12]:
df['drivers_list'].iloc[1]

'gAAAAABnP1ePWq-xbCGkf2IHHHmTawUmuYfrFnE6_bN7OxU7_nwUeC1gH93mSUhvKAK6ekDJHgrK3BeEDB4tF-EUfmLJU5B_aI5uaqFM1sYxoufHdtSFBl0='

In [13]:
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,drivers_list,request_hour,request_day_of_week,request_month,request_day_of_month
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...,8,1,6,27
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,gAAAAABnP1ePWq-xbCGkf2IHHHmTawUmuYfrFnE6_bN7Ox...,8,1,6,27
1,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1qF...,14,5,6,24
1,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,gAAAAABnP1eR9X2GGTL4IfToffXzXhqXagYjqQCTN172by...,14,5,6,24
2,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaT,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.00,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8-...,16,0,6,26

In [14]:
df['drivers_list'].iloc[1]

'gAAAAABnP1ePWq-xbCGkf2IHHHmTawUmuYfrFnE6_bN7OxU7_nwUeC1gH93mSUhvKAK6ekDJHgrK3BeEDB4tF-EUfmLJU5B_aI5uaqFM1sYxoufHdtSFBl0='

In [15]:
df['driver'] = df['drivers_list']
df.drop(columns=['drivers_list'], inplace=True)
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,request_hour,request_day_of_week,request_month,request_day_of_month,driver
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePWq-xbCGkf2IHHHmTawUmuYfrFnE6_bN7Ox...
1,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1qF...
1,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1eR9X2GGTL4IfToffXzXhqXagYjqQCTN172by...
2,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaT,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.00,16,0,6,26,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8-...

In [16]:
df.to_csv('data/test_data_v2_exploded.csv', index=False)

In [17]:
len(df)

251274

In [18]:
acceptance_rate_pivot = pd.read_csv('data/acceptance_rate_pivot.csv')

In [19]:
acceptance_rate_pivot.head()

,driver,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday
0,gAAAAABnP1eP--aUZjHDjjF1d2ZVQhqV5zDvQ7MvwFzL4m...,0.375000,1.0,1.00,0.666667,0.00000,0.000000,1.000000
1,gAAAAABnP1eP-0hm7X7pky2Su8OaitNnqLfuxHlIvp72tS...,0.000000,0.0,0.00,0.000000,0.00000,1.000000,0.333333
2,gAAAAABnP1eP-1e8_PnLOHgnnTIA7AqnElVW3qWcnXWj1D...,0.000000,0.0,0.00,1.000000,0.00000,0.000000,0.000000
3,gAAAAABnP1eP-1ucYmfswPEFjak_y4ZqsfcF8jAtYSU5O9...,0.666667,0.0,0.00,0.000000,0.00000,1.000000,0.000000
4,gAAAAABnP1eP-21hNsK-jiTx3LjuHi7o2JE40VoKX7rMYt...,0.058824,0.0,0.04,0.088889,0.03125,0.032258,0.125000

In [20]:
df = df.merge(acceptance_rate_pivot, on='driver', how='left')
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,request_hour,request_day_of_week,request_month,request_day_of_month,driver,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...,0.080357,0.029412,0.028571,0.023810,0.046512,0.040650,0.008475
1,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePWq-xbCGkf2IHHHmTawUmuYfrFnE6_bN7Ox...,0.571429,0.500000,0.625000,0.523810,0.583333,0.555556,0.416667
2,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1qF...,0.364865,0.415094,0.329114,0.271739,0.287500,0.298507,0.328358
3,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1eR9X2GGTL4IfToffXzXhqXagYjqQCTN172by...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.083333
4,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaT,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.00,16,0,6,26,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8-...,0.261905,0.303030,0.282051,0.294118,0.285714,0.210526,0.320000

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251274 entries, 0 to 251273
Data columns (total 36 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   requested_at               251274 non-null  datetime64[ns, UTC]
 1   updated_at                 251274 non-null  datetime64[ns, UTC]
 2   created_at                 251274 non-null  datetime64[ns, UTC]
 3   accepted_at                251274 non-null  datetime64[ns, UTC]
 4   started_at                 120296 non-null  datetime64[ns, UTC]
 5   cancel_date_time           130792 non-null  datetime64[ns, UTC]
 6   trip_id                    251274 non-null  object
 7   original_cost              251274 non-null  float64
 8   rider                      251274 non-null  object
 9   rider_profile_gender       251274 non-null  object
 10  rider_profile_rating       251274 non-null  float64
 11  estimated_distance         251274 non-null  int64
 12  estimated_eta              251274 non-null  float64
 13  is_coupon                  124311 non-null  float64
 14  isMultiStop                0 non-null       float64
 15  discount                   251274 non-null  float64
 16  is_booked                  251274 non-null  bool
 17  radius                     251274 non-null  int64
 18  dcc_distance               0 non-null       float64
 19  final_status               251274 non-null  object
 20  rider_rating               113889 non-null  float64
 21  yassir2driver              251274 non-null  float64
 22  driver2yassir              251274 non-null  float64
 23  discount_ratio_percent     182598 non-null  float64
 24  request_hour               251274 non-null  int32
 25  request_day_of_week        251274 non-null  int32
 26  request_month              251274 non-null  int32
 27  request_day_of_month       251274 non-null  int32
 28  driver                     251274 non-null  object
 29  acceptance_rate_monday     250587 non-null  float64
 30  acceptance_rate_tuesday    250587 non-null  float64
 31  acceptance_rate_wednesday  250587 non-null  float64
 32  acceptance_rate_thursday   250587 non-null  float64
 33  acceptance_rate_friday     250587 non-null  float64
 34  acceptance_rate_saturday   250587 non-null  float64
 35  acceptance_rate_sunday     250587 non-null  float64
dtypes: bool(1), datetime64[ns, UTC](6), float64(18), int32(4), int64(2), object(5)
memory usage: 63.5+ MB

In [22]:
columns_to_fill = ['acceptance_rate_monday', 'acceptance_rate_tuesday', 'acceptance_rate_wednesday', 'acceptance_rate_thursday',
                   'acceptance_rate_friday', 'acceptance_rate_saturday', 'acceptance_rate_sunday'
                   ]
df[columns_to_fill] = df[columns_to_fill].fillna(df[columns_to_fill].median())
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,request_hour,request_day_of_week,request_month,request_day_of_month,driver,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...,0.080357,0.029412,0.028571,0.023810,0.046512,0.040650,0.008475
1,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePWq-xbCGkf2IHHHmTawUmuYfrFnE6_bN7Ox...,0.571429,0.500000,0.625000,0.523810,0.583333,0.555556,0.416667
2,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1qF...,0.364865,0.415094,0.329114,0.271739,0.287500,0.298507,0.328358
3,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1eR9X2GGTL4IfToffXzXhqXagYjqQCTN172by...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.083333
4,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaT,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.00,16,0,6,26,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8-...,0.261905,0.303030,0.282051,0.294118,0.285714,0.210526,0.320000

In [23]:
df.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,request_hour,request_day_of_week,request_month,request_day_of_month,driver,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...,0.080357,0.029412,0.028571,0.023810,0.046512,0.040650,0.008475
1,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaT,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePWq-xbCGkf2IHHHmTawUmuYfrFnE6_bN7Ox...,0.571429,0.500000,0.625000,0.523810,0.583333,0.555556,0.416667
2,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1qF...,0.364865,0.415094,0.329114,0.271739,0.287500,0.298507,0.328358
3,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaT,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1eR9X2GGTL4IfToffXzXhqXagYjqQCTN172by...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.083333
4,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaT,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.00,16,0,6,26,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8-...,0.261905,0.303030,0.282051,0.294118,0.285714,0.210526,0.320000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251274 entries, 0 to 251273
Data columns (total 36 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   requested_at               251274 non-null  datetime64[ns, UTC]
 1   updated_at                 251274 non-null  datetime64[ns, UTC]
 2   created_at                 251274 non-null  datetime64[ns, UTC]
 3   accepted_at                251274 non-null  datetime64[ns, UTC]
 4   started_at                 120296 non-null  datetime64[ns, UTC]
 5   cancel_date_time           130792 non-null  datetime64[ns, UTC]
 6   trip_id                    251274 non-null  object
 7   original_cost              251274 non-null  float64
 8   rider                      251274 non-null  object
 9   rider_profile_gender       251274 non-null  object
 10  rider_profile_rating       251274 non-null  float64
 11  estimated_distance         251274 non-null  int64
 12  estimated_eta              251274 non-null  float64
 13  is_coupon                  124311 non-null  float64
 14  isMultiStop                0 non-null       float64
 15  discount                   251274 non-null  float64
 16  is_booked                  251274 non-null  bool
 17  radius                     251274 non-null  int64
 18  dcc_distance               0 non-null       float64
 19  final_status               251274 non-null  object
 20  rider_rating               113889 non-null  float64
 21  yassir2driver              251274 non-null  float64
 22  driver2yassir              251274 non-null  float64
 23  discount_ratio_percent     182598 non-null  float64
 24  request_hour               251274 non-null  int32
 25  request_day_of_week        251274 non-null  int32
 26  request_month              251274 non-null  int32
 27  request_day_of_month       251274 non-null  int32
 28  driver                     251274 non-null  object
 29  acceptance_rate_monday     251274 non-null  float64
 30  acceptance_rate_tuesday    251274 non-null  float64
 31  acceptance_rate_wednesday  251274 non-null  float64
 32  acceptance_rate_thursday   251274 non-null  float64
 33  acceptance_rate_friday     251274 non-null  float64
 34  acceptance_rate_saturday   251274 non-null  float64
 35  acceptance_rate_sunday     251274 non-null  float64
dtypes: bool(1), datetime64[ns, UTC](6), float64(18), int32(4), int64(2), object(5)
memory usage: 63.5+ MB

In [25]:
driver_acceptance_stats = pd.read_csv('data/driver_acceptance_stats.csv')

In [26]:

# Step 3: Merge these stats back into the original dataframe
df = df.merge(driver_acceptance_stats[['driver', 'acceptance_rate', 'total_accepted']], 
              on='driver', how='left')

# Rename for clarity in the final dataframe
df.rename(columns={'total_accepted': 'acceptance_count'}, inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251274 entries, 0 to 251273
Data columns (total 38 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   requested_at               251274 non-null  datetime64[ns, UTC]
 1   updated_at                 251274 non-null  datetime64[ns, UTC]
 2   created_at                 251274 non-null  datetime64[ns, UTC]
 3   accepted_at                251274 non-null  datetime64[ns, UTC]
 4   started_at                 120296 non-null  datetime64[ns, UTC]
 5   cancel_date_time           130792 non-null  datetime64[ns, UTC]
 6   trip_id                    251274 non-null  object
 7   original_cost              251274 non-null  float64
 8   rider                      251274 non-null  object
 9   rider_profile_gender       251274 non-null  object
 10  rider_profile_rating       251274 non-null  float64
 11  estimated_distance         251274 non-null  int64
 12  estimated_eta              251274 non-null  float64
 13  is_coupon                  124311 non-null  float64
 14  isMultiStop                0 non-null       float64
 15  discount                   251274 non-null  float64
 16  is_booked                  251274 non-null  bool
 17  radius                     251274 non-null  int64
 18  dcc_distance               0 non-null       float64
 19  final_status               251274 non-null  object
 20  rider_rating               113889 non-null  float64
 21  yassir2driver              251274 non-null  float64
 22  driver2yassir              251274 non-null  float64
 23  discount_ratio_percent     182598 non-null  float64
 24  request_hour               251274 non-null  int32
 25  request_day_of_week        251274 non-null  int32
 26  request_month              251274 non-null  int32
 27  request_day_of_month       251274 non-null  int32
 28  driver                     251274 non-null  object
 29  acceptance_rate_monday     251274 non-null  float64
 30  acceptance_rate_tuesday    251274 non-null  float64
 31  acceptance_rate_wednesday  251274 non-null  float64
 32  acceptance_rate_thursday   251274 non-null  float64
 33  acceptance_rate_friday     251274 non-null  float64
 34  acceptance_rate_saturday   251274 non-null  float64
 35  acceptance_rate_sunday     251274 non-null  float64
 36  acceptance_rate            250587 non-null  float64
 37  acceptance_count           250587 non-null  float64
dtypes: bool(1), datetime64[ns, UTC](6), float64(20), int32(4), int64(2), object(5)
memory usage: 67.3+ MB

In [28]:
columns_to_fill = ['acceptance_rate', 'acceptance_count']
df[columns_to_fill] = df[columns_to_fill].fillna(df[columns_to_fill].mean())

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251274 entries, 0 to 251273
Data columns (total 38 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   requested_at               251274 non-null  datetime64[ns, UTC]
 1   updated_at                 251274 non-null  datetime64[ns, UTC]
 2   created_at                 251274 non-null  datetime64[ns, UTC]
 3   accepted_at                251274 non-null  datetime64[ns, UTC]
 4   started_at                 120296 non-null  datetime64[ns, UTC]
 5   cancel_date_time           130792 non-null  datetime64[ns, UTC]
 6   trip_id                    251274 non-null  object
 7   original_cost              251274 non-null  float64
 8   rider                      251274 non-null  object
 9   rider_profile_gender       251274 non-null  object
 10  rider_profile_rating       251274 non-null  float64
 11  estimated_distance         251274 non-null  int64
 12  estimated_eta              251274 non-null  float64
 13  is_coupon                  124311 non-null  float64
 14  isMultiStop                0 non-null       float64
 15  discount                   251274 non-null  float64
 16  is_booked                  251274 non-null  bool
 17  radius                     251274 non-null  int64
 18  dcc_distance               0 non-null       float64
 19  final_status               251274 non-null  object
 20  rider_rating               113889 non-null  float64
 21  yassir2driver              251274 non-null  float64
 22  driver2yassir              251274 non-null  float64
 23  discount_ratio_percent     182598 non-null  float64
 24  request_hour               251274 non-null  int32
 25  request_day_of_week        251274 non-null  int32
 26  request_month              251274 non-null  int32
 27  request_day_of_month       251274 non-null  int32
 28  driver                     251274 non-null  object
 29  acceptance_rate_monday     251274 non-null  float64
 30  acceptance_rate_tuesday    251274 non-null  float64
 31  acceptance_rate_wednesday  251274 non-null  float64
 32  acceptance_rate_thursday   251274 non-null  float64
 33  acceptance_rate_friday     251274 non-null  float64
 34  acceptance_rate_saturday   251274 non-null  float64
 35  acceptance_rate_sunday     251274 non-null  float64
 36  acceptance_rate            251274 non-null  float64
 37  acceptance_count           251274 non-null  float64
dtypes: bool(1), datetime64[ns, UTC](6), float64(20), int32(4), int64(2), object(5)
memory usage: 67.3+ MB

In [30]:
df.columns

Index(['requested_at', 'updated_at', 'created_at', 'accepted_at', 'started_at',
       'cancel_date_time', 'trip_id', 'original_cost', 'rider',
       'rider_profile_gender', 'rider_profile_rating', 'estimated_distance',
       'estimated_eta', 'is_coupon', 'isMultiStop', 'discount', 'is_booked',
       'radius', 'dcc_distance', 'final_status', 'rider_rating',
       'yassir2driver', 'driver2yassir', 'discount_ratio_percent',
       'request_hour', 'request_day_of_week', 'request_month',
       'request_day_of_month', 'driver', 'acceptance_rate_monday',
       'acceptance_rate_tuesday', 'acceptance_rate_wednesday',
       'acceptance_rate_thursday', 'acceptance_rate_friday',
       'acceptance_rate_saturday', 'acceptance_rate_sunday', 'acceptance_rate',
       'acceptance_count'],
      dtype='object')

In [31]:
df.drop(columns=['requested_at', 'updated_at', 'created_at', 'accepted_at', 'started_at',
                 'cancel_date_time', 'rider_profile_gender', 'is_coupon',
                 'isMultiStop', 'is_booked', 'radius', 'dcc_distance',
                  'rider_rating', 
                 'discount_ratio_percent', 'request_day_of_month',
                 'rider', 'driver', 'trip_id', 'final_status'
                 ], inplace=True)

In [32]:
df.head()

,original_cost,rider_profile_rating,estimated_distance,estimated_eta,discount,yassir2driver,driver2yassir,request_hour,request_day_of_week,request_month,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday,acceptance_rate,acceptance_count
0,-0.249834,4.4,5282,827.0,0.30,1.666667,-0.504854,8,1,6,0.080357,0.029412,0.028571,0.023810,0.046512,0.040650,0.008475,0.034765,34.0
1,-0.249834,4.4,5282,827.0,0.30,1.666667,-0.504854,8,1,6,0.571429,0.500000,0.625000,0.523810,0.583333,0.555556,0.416667,0.526786,59.0
2,0.310963,4.6,13835,1205.0,0.22,0.250000,-0.504854,14,5,6,0.364865,0.415094,0.329114,0.271739,0.287500,0.298507,0.328358,0.322266,165.0
3,0.310963,4.6,13835,1205.0,0.22,0.250000,-0.504854,14,5,6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.083333,0.022727,1.0
4,-0.499668,4.6,227,48.0,0.00,0.000000,0.000000,16,0,6,0.261905,0.303030,0.282051,0.294118,0.285714,0.210526,0.320000,0.275229,60.0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251274 entries, 0 to 251273
Data columns (total 19 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   original_cost              251274 non-null  float64
 1   rider_profile_rating       251274 non-null  float64
 2   estimated_distance         251274 non-null  int64
 3   estimated_eta              251274 non-null  float64
 4   discount                   251274 non-null  float64
 5   yassir2driver              251274 non-null  float64
 6   driver2yassir              251274 non-null  float64
 7   request_hour               251274 non-null  int32
 8   request_day_of_week        251274 non-null  int32
 9   request_month              251274 non-null  int32
 10  acceptance_rate_monday     251274 non-null  float64
 11  acceptance_rate_tuesday    251274 non-null  float64
 12  acceptance_rate_wednesday  251274 non-null  float64
 13  acceptance_rate_thursday   251274 non-null  float64
 14  acceptance_rate_friday     251274 non-null  float64
 15  acceptance_rate_saturday   251274 non-null  float64
 16  acceptance_rate_sunday     251274 non-null  float64
 17  acceptance_rate            251274 non-null  float64
 18  acceptance_count           251274 non-null  float64
dtypes: float64(15), int32(3), int64(1)
memory usage: 33.5 MB

In [34]:
right_order =   ['original_cost', 'rider_profile_rating', 'estimated_distance',
       'estimated_eta', 'discount', 'yassir2driver',
       'driver2yassir', 'request_hour', 'request_day_of_week',
       'request_month', 'acceptance_rate_monday', 'acceptance_rate_tuesday',
       'acceptance_rate_wednesday', 'acceptance_rate_thursday',
       'acceptance_rate_friday', 'acceptance_rate_saturday',
       'acceptance_rate_sunday', 'acceptance_rate', 'acceptance_count'
       ]
df = df[right_order]

In [35]:
df.to_csv('data/data_final_test.csv', index=False)