In [25]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [26]:
X = pd.read_csv('data/data_final_test.csv')
X.head()

,original_cost,rider_profile_rating,estimated_distance,estimated_eta,discount,yassir2driver,driver2yassir,request_hour,request_day_of_week,request_month,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday,acceptance_rate,acceptance_count
0,-0.249834,4.4,5282,827.0,0.30,1.666667,-0.504854,8,1,6,0.080357,0.029412,0.028571,0.023810,0.046512,0.040650,0.008475,0.034765,34.0
1,-0.249834,4.4,5282,827.0,0.30,1.666667,-0.504854,8,1,6,0.571429,0.500000,0.625000,0.523810,0.583333,0.555556,0.416667,0.526786,59.0
2,0.310963,4.6,13835,1205.0,0.22,0.250000,-0.504854,14,5,6,0.364865,0.415094,0.329114,0.271739,0.287500,0.298507,0.328358,0.322266,165.0
3,0.310963,4.6,13835,1205.0,0.22,0.250000,-0.504854,14,5,6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.083333,0.022727,1.0
4,-0.499668,4.6,227,48.0,0.00,0.000000,0.000000,16,0,6,0.261905,0.303030,0.282051,0.294118,0.285714,0.210526,0.320000,0.275229,60.0

In [27]:
X.drop(columns=['estimated_distance'], inplace=True)

In [28]:
X.head()

,original_cost,rider_profile_rating,estimated_eta,discount,yassir2driver,driver2yassir,request_hour,request_day_of_week,request_month,acceptance_rate_monday,acceptance_rate_tuesday,acceptance_rate_wednesday,acceptance_rate_thursday,acceptance_rate_friday,acceptance_rate_saturday,acceptance_rate_sunday,acceptance_rate,acceptance_count
0,-0.249834,4.4,827.0,0.30,1.666667,-0.504854,8,1,6,0.080357,0.029412,0.028571,0.023810,0.046512,0.040650,0.008475,0.034765,34.0
1,-0.249834,4.4,827.0,0.30,1.666667,-0.504854,8,1,6,0.571429,0.500000,0.625000,0.523810,0.583333,0.555556,0.416667,0.526786,59.0
2,0.310963,4.6,1205.0,0.22,0.250000,-0.504854,14,5,6,0.364865,0.415094,0.329114,0.271739,0.287500,0.298507,0.328358,0.322266,165.0
3,0.310963,4.6,1205.0,0.22,0.250000,-0.504854,14,5,6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.083333,0.022727,1.0
4,-0.499668,4.6,48.0,0.00,0.000000,0.000000,16,0,6,0.261905,0.303030,0.282051,0.294118,0.285714,0.210526,0.320000,0.275229,60.0

In [29]:
from xgboost import XGBClassifier

In [32]:
model = XGBClassifier()
model.load_model('xgboost_model.json')

In [33]:
y_pred = model.predict(X)
y_pred_proba = model.predict_proba(X)[:, 1]
y_pred, y_pred_proba

(array([0, 0, 0, ..., 0, 0, 0]),
 array([0.0053842 , 0.3375347 , 0.31208408, ..., 0.18481605, 0.34879982,
        0.00177842], dtype=float32))

In [34]:
probabilities = model.predict_proba(X)[:, 1]  # Get probabilities for the positive class

In [35]:
test = pd.read_csv('data/test_data_v2_exploded.csv')
test.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,request_hour,request_day_of_week,request_month,request_day_of_month,driver
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaN,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...
1,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaN,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePWq-xbCGkf2IHHHmTawUmuYfrFnE6_bN7Ox...
2,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaN,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1qF...
3,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaN,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1eR9X2GGTL4IfToffXzXhqXagYjqQCTN172by...
4,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaN,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.00,16,0,6,26,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8-...

In [36]:
len(X), len(test)

(251274, 251274)

In [37]:
test['probability'] = probabilities

In [38]:
test.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,request_hour,request_day_of_week,request_month,request_day_of_month,driver,probability
0,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaN,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePcM-5qyZJunqrkNGXfGY0kg0cN8E2Vn8kls...,0.005384
1,2023-06-27 08:59:44.483000+00:00,2023-06-28 18:55:05.261000+00:00,2023-06-27 08:59:44.486000+00:00,2023-06-27 09:00:19.301000+00:00,2023-06-27 09:33:06.369000+00:00,NaN,gAAAAABnP1elvS1ctPBIUi4iLVbJWY-W-KyCP9LULCJMLj...,-0.249834,gAAAAABnP1eDGUPBbDHOTvmiwE1HFsJzIPjYHGQhybDg3_...,/,4.4,5282,827.0,1.0,NaN,0.30,False,4000,NaN,FINISHED,5.0,1.666667,-0.504854,0.30,8,1,6,27,gAAAAABnP1ePWq-xbCGkf2IHHHmTawUmuYfrFnE6_bN7Ox...,0.337535
2,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaN,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1ePEsXdUuxrN01W06UELJVa26tclcE2BqN1qF...,0.312084
3,2023-06-24 14:46:23.950000+00:00,2023-06-24 14:53:53.188000+00:00,2023-06-24 14:46:23.954000+00:00,2023-06-24 14:46:54.771000+00:00,NaN,2023-06-24 14:53:51.209000+00:00,gAAAAABnP1ewrlc5qbu8CpBUb4tHNc2yragN0ldGU73jvY...,0.310963,gAAAAABnP1eD-w_DR8JB--mZxg6IoJ0AgYEleXDP7jgi4j...,/,4.6,13835,1205.0,1.0,NaN,0.22,False,4000,NaN,NOT_FINISHED,NaN,0.250000,-0.504854,0.22,14,5,6,24,gAAAAABnP1eR9X2GGTL4IfToffXzXhqXagYjqQCTN172by...,0.004033
4,2023-06-26 16:19:46.415000+00:00,2023-06-26 17:29:54.672000+00:00,2023-06-26 16:19:46.418000+00:00,2023-06-26 16:20:39.629000+00:00,2023-06-26 16:31:55.474000+00:00,NaN,gAAAAABnP1ehaIpRIaF2K1R9cHSEKqRp_0WhYJe4h9X20k...,-0.499668,gAAAAABnP1eEpo-ShYaUs7f1wAvRj9h6GpPROj7zSbT_0Z...,/,4.6,227,48.0,NaN,NaN,0.00,False,4000,NaN,FINISHED,5.0,0.000000,0.000000,0.00,16,0,6,26,gAAAAABnP1ePwIZ4V8qcu6xJov17SivdF4580bZP8knu8-...,0.207076

In [39]:
# test = test.sort_values(by=['probability'], ascending=[False])
test = test.sort_values(by=['trip_id', 'probability'], ascending=[True, False])

In [40]:
test.head()

,requested_at,updated_at,created_at,accepted_at,started_at,cancel_date_time,trip_id,original_cost,rider,rider_profile_gender,rider_profile_rating,estimated_distance,estimated_eta,is_coupon,isMultiStop,discount,is_booked,radius,dcc_distance,final_status,rider_rating,yassir2driver,driver2yassir,discount_ratio_percent,request_hour,request_day_of_week,request_month,request_day_of_month,driver,probability
103144,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaN,gAAAAABnP1ef--3vFfAOJgEf3-RyA9pTm-pfjWAGOxkXhj...,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,5.0,0.833333,-0.504854,NaN,12,2,2,22,gAAAAABnP1ePtCB-IqV5JTijXkgcUUSl3bhYQQ-WljKidI...,0.559447
103143,2023-02-22 12:11:10.845000+00:00,2023-02-24 16:03:39.591000+00:00,2023-02-22 12:11:10.849000+00:00,2023-02-22 12:11:35.589000+00:00,2023-02-22 12:16:14.608000+00:00,NaN,gAAAAABnP1ef--3vFfAOJgEf3-RyA9pTm-pfjWAGOxkXhj...,-0.499668,gAAAAABnP1eDUswUacbBo2XFZRijFgYDAhLGEYN3fELQPO...,HOMME,4.7,1315,285.0,1.0,NaN,0.25,False,4000,NaN,FINISHED,5.0,0.833333,-0.504854,NaN,12,2,2,22,gAAAAABnP1ePSUralyqcKVNakVKyfpgqvUXUzpZ6gm_5aQ...,0.119168
115788,2023-04-11 12:15:24.231000+00:00,2023-04-14 15:16:21.092000+00:00,2023-04-11 12:15:24.236000+00:00,2023-04-11 12:15:52.189000+00:00,2023-04-11 12:30:14.322000+00:00,NaN,gAAAAABnP1ef-0x_-SjCclHT6ZHjGtk2zwkOEKU6qCvXR1...,-0.499668,gAAAAABnP1eDeJ8UrTpqNa-gOpHkTxQP8o01PAmWU93t4W...,/,4.6,2295,483.0,1.0,NaN,0.20,False,4000,NaN,FINISHED,5.0,0.000000,-0.485437,NaN,12,1,4,11,gAAAAABnP1ePLp-bSpUSD6Kban6TvHJZQv9U0ilJGLtZs0...,0.683852
115789,2023-04-11 12:15:24.231000+00:00,2023-04-14 15:16:21.092000+00:00,2023-04-11 12:15:24.236000+00:00,2023-04-11 12:15:52.189000+00:00,2023-04-11 12:30:14.322000+00:00,NaN,gAAAAABnP1ef-0x_-SjCclHT6ZHjGtk2zwkOEKU6qCvXR1...,-0.499668,gAAAAABnP1eDeJ8UrTpqNa-gOpHkTxQP8o01PAmWU93t4W...,/,4.6,2295,483.0,1.0,NaN,0.20,False,4000,NaN,FINISHED,5.0,0.000000,-0.485437,NaN,12,1,4,11,gAAAAABnP1ePDeoDQD4Rz6w2R9vzxAIL_d5v6RWH7D4LDA...,0.451186
115790,2023-04-11 12:15:24.231000+00:00,2023-04-14 15:16:21.092000+00:00,2023-04-11 12:15:24.236000+00:00,2023-04-11 12:15:52.189000+00:00,2023-04-11 12:30:14.322000+00:00,NaN,gAAAAABnP1ef-0x_-SjCclHT6ZHjGtk2zwkOEKU6qCvXR1...,-0.499668,gAAAAABnP1eDeJ8UrTpqNa-gOpHkTxQP8o01PAmWU93t4W...,/,4.6,2295,483.0,1.0,NaN,0.20,False,4000,NaN,FINISHED,5.0,0.000000,-0.485437,NaN,12,1,4,11,gAAAAABnP1ePyrfYnbctxFMZzGAI8VQF3_uSKADyKihNZP...,0.412007

In [41]:
test.iloc[0]['trip_id']

'gAAAAABnP1ef--3vFfAOJgEf3-RyA9pTm-pfjWAGOxkXhjgJr5emFv7P5V9Qfh_dE4g0lGJUyAySP7IlQ3ROI3hWHV5fvn84Pw=='

In [42]:
test.iloc[0]['driver']

'gAAAAABnP1ePtCB-IqV5JTijXkgcUUSl3bhYQQ-WljKidIpqfEUcEtio8fZlhqewkOBYiZ4SCFKRpRGhCE2o6A7dJCY4ew2Kxj1RjIECUHQQlQUlqPceFDI='

In [43]:
test.iloc[1]['driver']

'gAAAAABnP1ePSUralyqcKVNakVKyfpgqvUXUzpZ6gm_5aQ9EFhCAitIcsxLCDnplrB4j14_PtECmidJANBi-IBp_rcJAr9JKOvFKlLPV55kGR90RPsuFYLM='

In [44]:
result = (
    test.sort_values(by=['trip_id', 'probability'], ascending=[True, False])  # Ensure correct order
    .groupby('trip_id')
    .agg({'driver': list})  # Aggregate driver_id into a list
    .reset_index()  # Optional: reset the index for a clean DataFrame
)

# Rename the aggregated column if needed
result.rename(columns={'driver': 'drivers_list'}, inplace=True)

result.head()

,trip_id,drivers_list
0,gAAAAABnP1ef--3vFfAOJgEf3-RyA9pTm-pfjWAGOxkXhj...,[gAAAAABnP1ePtCB-IqV5JTijXkgcUUSl3bhYQQ-WljKid...
1,gAAAAABnP1ef-0x_-SjCclHT6ZHjGtk2zwkOEKU6qCvXR1...,[gAAAAABnP1ePLp-bSpUSD6Kban6TvHJZQv9U0ilJGLtZs...
2,gAAAAABnP1ef-110gercXwTHaP3QntWQazduU6iVxPlYzq...,[gAAAAABnP1eP0Z3aV0bb0ybuvk_0miMyJzzMcunWQ4ez_...
3,gAAAAABnP1ef-2qNtESPFoTFIfmajXg32sjHz3dwp2bTrB...,[gAAAAABnP1ePSaXp3t4r39Q2onVuFW-ODeaNcKo_B1fXD...
4,gAAAAABnP1ef-3n8kR8K5oGcysohnNIvlf_yQsOaRlICcb...,[gAAAAABnP1eP7CHxlHGpdOSNXnq7BcIN3qBTjYYLgb72n...

In [45]:
result.iloc[0]['drivers_list']

['gAAAAABnP1ePtCB-IqV5JTijXkgcUUSl3bhYQQ-WljKidIpqfEUcEtio8fZlhqewkOBYiZ4SCFKRpRGhCE2o6A7dJCY4ew2Kxj1RjIECUHQQlQUlqPceFDI=',
 'gAAAAABnP1ePSUralyqcKVNakVKyfpgqvUXUzpZ6gm_5aQ9EFhCAitIcsxLCDnplrB4j14_PtECmidJANBi-IBp_rcJAr9JKOvFKlLPV55kGR90RPsuFYLM=']

In [46]:
result.columns

Index(['trip_id', 'drivers_list'], dtype='object')

In [47]:
result.iloc[0]['drivers_list']

['gAAAAABnP1ePtCB-IqV5JTijXkgcUUSl3bhYQQ-WljKidIpqfEUcEtio8fZlhqewkOBYiZ4SCFKRpRGhCE2o6A7dJCY4ew2Kxj1RjIECUHQQlQUlqPceFDI=',
 'gAAAAABnP1ePSUralyqcKVNakVKyfpgqvUXUzpZ6gm_5aQ9EFhCAitIcsxLCDnplrB4j14_PtECmidJANBi-IBp_rcJAr9JKOvFKlLPV55kGR90RPsuFYLM=']

In [48]:
result['drivers_ranking'] = result['drivers_list']
result.drop(columns=['drivers_list'], inplace=True)

In [50]:
result.to_csv('data/submission.csv', index=False)